// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAecxMcPkkb1UJ-BW9c34Z4i266N4VSjYI',
    appId: '1:524814608778:web:45edb869ffccf013908073',
    messagingSenderId: '524814608778',
    projectId: 'diabetes-tfg-app',
    authDomain: 'diabetes-tfg-app.firebaseapp.com',
    storageBucket: 'diabetes-tfg-app.firebasestorage.app',
    measurementId: 'G-9GVH7G0HP2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZX1Xkxkakvb9_xA41tzOaXB6ejbIjw9E',
    appId: '1:524814608778:android:8d349bc7793ef399908073',
    messagingSenderId: '524814608778',
    projectId: 'diabetes-tfg-app',
    storageBucket: 'diabetes-tfg-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_xTa6ZuTRnzBnYkOiMvTLizpI5L86QTk',
    appId: '1:524814608778:ios:f04f951550696872908073',
    messagingSenderId: '524814608778',
    projectId: 'diabetes-tfg-app',
    storageBucket: 'diabetes-tfg-app.firebasestorage.app',
    iosBundleId: 'com.example.diabetesTfgApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_xTa6ZuTRnzBnYkOiMvTLizpI5L86QTk',
    appId: '1:524814608778:ios:f04f951550696872908073',
    messagingSenderId: '524814608778',
    projectId: 'diabetes-tfg-app',
    storageBucket: 'diabetes-tfg-app.firebasestorage.app',
    iosBundleId: 'com.example.diabetesTfgApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAecxMcPkkb1UJ-BW9c34Z4i266N4VSjYI',
    appId: '1:524814608778:web:cfef7ccd0780aa60908073',
    messagingSenderId: '524814608778',
    projectId: 'diabetes-tfg-app',
    authDomain: 'diabetes-tfg-app.firebaseapp.com',
    storageBucket: 'diabetes-tfg-app.firebasestorage.app',
    measurementId: 'G-E0XJGGF7R1',
  );
}
